---
# FEATURE_NAME: build_and_dispatch_docker_images
# FEATURE_VERSION: build_and_dispatch_docker_images-v5.1.3
# FEATURE_URL: https://github.com/prefapp/features/tree/build_and_dispatch_docker_images-v5.1.3/packages/build_and_dispatch_docker_images

name: Verify build_and_dispatch_docker_images config files

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read


jobs:
  validate-yaml:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 #v3.0.2
        id: check_file_changed
        with:
          list-files: shell
          filters: |
            configs:
              - added|modified: '.github/*.yaml'
              - added|modified: '.github/*.yml'

      - name: Verify configs
        if: steps.check_file_changed.outputs.configs == 'True'
        run: yamllint -c .github/.yamllint.conf ${{ steps.check_file_changed.outputs.configs_files }}
